### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#10]
## List

```
create
create-web
create-native
prefix-client
prefix-server
transpile-web
transpile-native
validate
```

## `create`

```js
import { createLayoutStyles, createTextStyles } from '@lada/create'
import { createLayoutStyles, createTextStyles } from '@lada/create-web'
import { createLayoutStyles, createTextStyles } from '@lada/create-native'
```

Where `create` is a meta-package with different entry points in `package.json`:

```js
"main": "index.web.js",
"react-native": "index.native.js"
```

AFAIK this `react-native` should do the trick.

So if you are not using RN then you just don't need to install it, use `create-web`. Same for RN only. Using both RN and web – install a universal `create`. Packages composition.

Our main "external" packages.

## `prefix-client` / `prefix-server`

```js
import prefixStyles from '@lada/prefix-client'
import prefixStyles from '@lada/prefix-server'
```

Internal packages (in most cases).

## `transpile-web` / `transpile-native`

```js
import { transpileLayoutStyles, transpileTextStyles } from '@lada/transpile-web'
import { transpileLayoutStyles, transpileTextStyles } from '@lada/transpile-native'
```

Internal packages (in most cases).

## `validate`

```js
import { validateLayoutStyles, validateTextStyles } from '@lada/validate'
```

Internal package (in most cases). Should be the same for RN and web.

**Comment by deepsweet** [comment]
@xaviervia ⬆︎

**Comment by xaviervia** [comment]
Looks good

**Comment by deepsweet** [comment]
Ok, going to work on `create` and `create-web` packages then.
