### ISSUE TITLE
Rename `content.size` to `content.dimensions` in layout styles?

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#16]

**Comment by xaviervia** [comment]
For consistency with `text`?

**Comment by deepsweet** [comment]
yes. also, do we need to group it at all inside of `dimensions`?.. it's 2 props, `width` and `height` :thinking:

**Comment by xaviervia** [comment]
It’s not about the amount of props... is more like there could be a different set of `width` and `height`.

But you are right, I think it’s pointless. They are the width and height of the thing itself. There is no need to wrap them. Let’s get rid of the wrapper, and the same for the `text` one.

**Comment by deepsweet** [comment]
:+1: 

I think that main and very literal idea of making some wrappers is to get rid of camel-cased props like `borderWidth` and `borderColor`, to "unflat". If `width` is just width and `height` is just height, then probably there is no point to wrap them.
