### ISSUE TITLE
Add `position: 'center'` to Layout styles?

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#29]
Where `'center'` means `50% 50%`.

**Comment by xaviervia** [comment]
What is the difference between this and `content: { align: { horizontally: 'center', vertically: 'center' } }`

**Comment by deepsweet** [comment]
we need to create a modal dialog above some form as an example then. I'm not quite sure that we can get rid of "in flow" and "out if flow" CSS concepts.

**Comment by deepsweet** [comment]
also by following this logic we don't need a `position` at all?
