### ISSUE TITLE
Try JSONSchema validation instead of PropTypes

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#3]
* https://github.com/mafintosh/is-my-json-valid
* http://json-schema.org/

Probably it's more powerful, flexible and easier to customize.

I implemented a [silly `onlyShape`](https://github.com/batata-frita/lada/commit/aa092eab9237c49efaaada56f37bdc71159bd84e) with PropTypes to error on any extra-non-declared style props, but it doesn't work with first level of propTypes object keys. This functionality requires [more hacks](https://github.com/airbnb/prop-types-exact/blob/master/src/index.js) 🤷‍♂️

**Comment by xaviervia** [comment]
On this spirit, we could also provide Flow type definitions
