### ISSUE TITLE
How to specify `position: fixed`?

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#31]
* `isFixed` – doesn't explain a lot.

**Comment by xaviervia** [comment]
I think we should not support this:

1. it is very simple to do this just by having a scrollable view inside a view that has the same size as the window. anything that should be "fixed" can be done as a child of the view that contains the scrollable one
2. It is fundamentally broken in iOS, and flaky in other browsers
3. it is kind of a weird feature. being able to really easily change the size of your things according to the window size, there is no reason not to go with the "fullscreen view" with the scrollable view inside approach, which is more robust

Also the "view with scrollable view inside" approach can be demoed and tested in divs, and does not require weird iframes or anything like that. and works in web and native.
