### ISSUE TITLE
Are we going to continue using a Start preset for monorepo?

### ISSUE THREAD

**Issue by deepsweet** [batata-frita/lada#6]
I mean do you like it? :) I'm going to work further on the idea because of a `@hocs` project in any way.

Right now we are using my own preset for my personal projects with a custom ESLint stuff (that's why we had to manually install Standard and related packages here), but I can create a preset for Lada with Standard included. In a perfect world you should be able to have only 1-2 dev dependencies.

**Comment by xaviervia** [comment]
It’s great! It’s very easy to use and makes a lot of sense, I think we can keep it, for sure.

**Comment by deepsweet** [comment]
Ok, this one is next in my queue so that we can get Travis and finally publishing then.

**Comment by deepsweet** [comment]
I'm going to get rid of a preset in favor of locally installed Start stuff, it's too much specific.
